name: geohippy
channels:
  - conda-forge
  - https://repo.platform.here.com/artifactory/api/conda/olp_analytics/analytics_sdk
dependencies:
  - python=3.9
  - awkward1
  - cmake
  - datashader
  - diagrams
  - emacs
  - fastapi
  - folium
  - geemap
  - geopy
  - graphviz
  - ipycanvas
  - ipycytoscape
  - ipydatagrid
  - ipygany
  - ipylab
  - jupyterlab
  - jupyterlab-cell-flash
  - jupyterlab-geojson
  - jupyterlab-tour
  - jupyter-server-proxy
  - leafmap
  - lux-api
  - mamba_gator
  - myst-parser
  - nodejs
  - xyzspaces
  - here-location-services
  - here-map-widget-for-jupyter
  - here-content=2.4.0
  - here-geopandas-adapter=2.4.0
  - here-geotiles=2.4.0
  - here-inspector=2.4.0
  - here-platform=2.4.0
  - osmnx
  - pre-commit
  - pip
  - pip:
     - flatdata-py
     - jupyterlab-language-pack-de-DE
     - jupyterlab-language-pack-es-ES
     - jupyterlab-language-pack-fr-FR
     - jupyterlab-language-pack-ja-JP
     - jupyterlab-language-pack-ru-RU
     - jupyterlab-language-pack-uk-UA
     - jupyterlab-language-pack-zh-CN
     - jupyterlab-language-pack-zh-TW
     - overpass
     - sphinxawesome-theme
  - plotly
  - pydeck
  - pyngrok
  - pyrosm
  - ray-core
  - seaborn
  - sphinx
  - sphinx_rtd_theme
  - streamlit
  - tqdm
  - turfpy
  - voila
  - yarn
  - xarray
